# Site settings
baseurl: /
title: Max Lever
email: maxdavidlever@gmail.com
description: |
  Hello! I'm a French-American artist, designer, and software engineer. I am a recent graduate of Northeastern University, where I studied computer science, interactive media, and philosophy. I've also taken courses in political science and philosophy at Sciences Po in Paris.

  I am interested in the effects of emerging technologies on society, and in building into technologies a critical understanding of humanity.

  I've previously worked at:

  The MIT Media Lab, an antidisciplinary institution, designing an interface which allows you to compute the emotional content of sentences, and detect sarcasm.

  Ronik Design, a creative technology agency in New York, designing and developing digital experiences for clients big and small.

  I'm seeking new collaborations. If you're interested in building creative and critical technologies (or want to learn the right way to cut cheese), reach me at maxdavidlever[at]gmail.com.

baseurl: ""
url: "https://maxlever.me"
linkedin_username: maxlever
github_username:  maxlever
devpost_username: maxlever

# Build settings
markdown: kramdown

# multilang support
gems:
  - jekyll-polyglot
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascripts", "images", "css"]
parallel_localization: true
