# Site settings
baseurl: /
title: Max Lever
email: maxdavidlever@gmail.com
description: |
<<<<<<< HEAD
  Hello! I'm a French-American artist, designer, and software engineer, and a recent graduate of Northeastern University, where I studied computer science, interactive media, and philosophy. I've also taken courses in political science and philosophy at Sciences Po in Paris.

  Knowing several systems—web technologies, design systems, cultures—from the inside and the outside, allows me to reveal them, make them legible.

  Most critically, I hope to recover an underlying physicality in technology that can be diminished in virtual interactions. The smartphone, which my generation checks 150 times daily, has replaced many processes that formerly involved physical interactions (postman, teller, etc.). In this environment, the dominant paradigm represents human experience and people as metrics, and it is easier to harm when others are just numbers. My goal is to create art that uses the medium of technology to remind us of our own physicality while revealing how technology structures our behavior.
=======
  Hello! I'm a French-American artist, designer, and software engineer, and a graduate of Northeastern University, where I studied computer science, interactive media, and philosophy. I've also taken courses in political science and philosophy at Sciences Po in Paris.
>>>>>>> tweaks

  I've previously worked at the MIT Media Lab, where I designed an interface which allows you to compute the emotional content of sentences, and detect sarcasm.

  At Ronik Design, a creative technology agency in New York, I designed and built digital experiences for a diversity of clients.

  Knowing several systems—web technologies, design systems, cultures—from the inside and the outside, allows me to reveal them, make them legible.

  Most critically, I hope to recover an underlying physicality in technology that can be diminished in virtual interactions. The smartphone, which my generation checks 150 times daily, has replaced many processes that formerly involved physical interactions (postman, teller, etc.). In this environment, the dominant paradigm represents human experience and people as metricss, and it is easier to harm when others are just numbers. My goal is to create art that uses the medium of technology to remind us of our own physicality while revealing how technology structures our behavior.

  I'm seeking new collaborations. If you're interested in building creative and critical technologies (or want to learn the right way to cut cheese), reach me at maxdavidlever[at]gmail.com.
description-fr: |
  Artiste, designer graphique, et ingénieur logiciel franco-américain, j'ai obtenu un Bachelor of Science en informatique, design intéractif et philosophie morale de l'université Northeastern à Boston. J'ai également suivi des cours à Sciences Po Paris.

  J'ai récemment rejoint le MIT Media Lab, un groupe de recherche qui se dit « antidisciplinaire », au sein duquel j'ai créé une interface donnant accès à une intelligence artificielle qui détecte les émotions de n'importe quelle phrase, ainsi que le sarcasme. J'ai également travaillé pour l'agence Ronik Design à New York sur des projets de design et de développement web.

  Ce qui m'intéresse, c'est l'effet des nouvelles technologies sur notre société. J'espère intégrer un esprit critique et une compréhension humaine dans les technologies que je crée.

  Si vous avez un projet en tête, n'hesitez pas à prendre contact à l'adresse maxdavidlever[arobase]gmail.com.
baseurl: ""
url: "https://maxlever.me"
linkedin_username: maxlever
github_username:  maxlever
devpost_username: maxlever

# Build settings
markdown: kramdown

# multilang support
# gems:
#   - jekyll-polyglot
# plugins:
#   - jekyll-polyglot
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascripts", "images", "css"]
# parallel_localization: true
