# Site settings
title: Max Lever
email: maxlever@ccs.neu.edu
description: |
  I'm a French-American student in my 4th year at Northeastern University, in Boston, where I study Computer Science and Interactive Media. Currently, I'm taking courses in political science and philosophy at Sciences Po, in Paris. My interests are at the confluence of design, technology, and social impact. I spend my time analyzing systems, whether they are graphic, technological, philosophical, or political. My practical experience includes design thinking, software development, interaction design, and digital/interactive art.

  Otherwise, I occupy myself by reading philosophical novels, drawing convoluted diagrams, or making lists; usually while eating crunchy pastries or bread.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maxlever.me" # the base hostname & protocol for your site
linkedin_username: maxlever
github_username:  maxlever

# Build settings
markdown: kramdown
