# Site settings
baseurl: /
title: Max Lever
email: maxlever@ccs.neu.edu
description: |
  I'm a French-American student at Northeastern University, where I study Computer Science, Interactive Media, and Ethics. I've also taken courses in political science and philosophy at Sciences Po in Paris. I enjoy analyzing and building systems, whether they are graphic, technical, or conceptual.
  
  I've previously worked at the MIT Media Lab, designing an interface which allows you to compute the emotional content of sentences, and detect sarcasm. 
  
  I've also worked at Ronik Design, a creative technology agency in New York, designing and developing digital experiences for clients big and small.
  
  I love having interdisciplinary and critical conversations. If you're interested in a collaboration, or just want to chat, reach me at maxlever[at]ccs.neu.edu.
baseurl: ""
url: "https://maxlever.me"
linkedin_username: maxlever
github_username:  maxlever
devpost_username: maxlever

# Build settings
markdown: kramdown

# multilang support
gems:
  - jekyll-polyglot
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascripts", "images", "css"]
parallel_localization: true
