# Site settings
baseurl: /
title: Max Lever
email: maxlever@ccs.neu.edu
description: |
  I'm a French-American student at Northeastern University, where I study Computer Science and Interactive Media. I've also taken courses in political science and philosophy at Sciences Po in Paris. I enjoy analyzing and building systems, whether they are graphic, technical, or conceptual.
  
  Currently, I'm working at the MIT Media Lab designing a web interface for Machine Learning sentiment analysis.
  
  Reach me at maxlever[at]ccs.neu.edu.
baseurl: ""
url: "https://maxlever.me"
linkedin_username: maxlever
github_username:  maxlever
devpost_username: maxlever

# Build settings
markdown: kramdown

# multilang support
gems:
  - jekyll-polyglot
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascripts", "images", "css"]
parallel_localization: true
