# Site settings
baseurl: /
title: Max Lever
email: maxdavidlever@gmail.com
description: 
  <p>Hello! I'm a French-American artist, designer, and developer. I am a back-end engineer at Axios, helping readers learn about the world and make them smarter, faster. Previously, I was the lead software engineer at <a href='http://artmatr.co'>Artmatr</a>, building painting robots. I also worked for <a href='http://metalab.harvard.edu'>metaLAB (at) Harvard</a>, where I built art installations about AI ethics, and the <a href='http://media.mit.edu'>MIT Media Lab</a>, where I built design tools for connecting concepts and provoking new ideas, and an AI-based interface for computing the emotional content of sentences.</p>
  <p>I am a graduate of Northeastern University, where I studied computer science, design, and ethics. I've also taken courses in political science and philosophy at Sciences Po in Paris.</p>
  <p>I aim to make virtual interactions more empathetic, and make users more aware of their physicality. The smartphone, which my generation checks 150 times daily, has replaced many processes that formerly involved physical interactions (postman, teller, etc.). In this environment, the dominant paradigm represents human experience and people as metrics, and it is easier to harm when others are just numbers. My goal is to create art that uses the medium of technology to remind us of our own physicality while revealing how technology structures our behavior.</p>
  <p>I'm always seeking new collaborations. If you're interested in building creative and critical technologies, reach me at maxdavidlever[at]gmail.com.</p>
description-fr: |
  <p>Ingénieur logiciel franco-américain, (ainsi qu'un artiste et designer) je travaille actuellement à <a href="https://axios.com">Axios</a>. J'ai précédemment travaillé à Artmatr sur des robots peintres ainsi qu'au MIT Media Lab, sur une interface donnant accès à une IA qui détecte les émotions de n'importe quelle phrase, ainsi que le sarcasme. J'ai aussi réalisé des installations artistiques pour le metaLAB de Harvard.</p>
  <p>J'ai obtenu ma licence en 2018 en informatique, design et éthique de l'université Northeastern à Boston. J'ai également suivi des cours à Sciences Po Paris.</p>
  <p>Ce qui m'intéresse, c'est l'effet des nouvelles technologies sur notre société. J'espère intégrer un esprit critique et une compréhension humaine dans les technologies que je crée.</p>
  <p>Si vous avez un projet en tête, n'hésitez pas à prendre contact à l'adresse maxdavidlever[arobase]gmail.com.</p>
baseurl: ""
url: "https://maxlever.me"
linkedin_username: maxlever
github_username:  maxlever
devpost_username: maxlever

# Build settings
markdown: kramdown

# multilang support
# gems:
#   - jekyll-polyglot
# plugins:
#   - jekyll-polyglot
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascripts", "images", "css"]
# parallel_localization: true
include: [".well-known"]
